server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: shakib19
    url: jdbc:mysql://localhost:3306/bookApp
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
